SELECT * FROM customer JOIN customer_type ON customer_type.customer_type_id = customer.customer_type_id WHERE customer_status = 1;
SELECT * FROM customer JOIN customer_type ON customer_type.customer_type_id = customer.customer_type_id;
SELECT * FROM case_study.customer;
INSERT INTO customer (customer_type_id,customer_name,customer_birthday,customer_gender,customer_id_card,customer_phone,customer_email,customer_address,customer_status) VALUES (2,"ABC","2000-12-12",0,"123123123","0912121212","xyz@gmail.com","123 XXX",0);
UPDATE customer SET customer_type_id= 2, customer_name = "A", customer_birthday = "2022-01-01", customer_gender=1, customer_id_card="0101010101",customer_phone="090123123",customer_email="test@gmail.com",customer_address="123 QWERTY" WHERE customer_id = 14;
SELECT * FROM customer JOIN customer_type ON customer_type.customer_type_id = customer.customer_type_id WHERE customer_id=14;
UPDATE customer SET customer_status = 1 WHERE customer_id = 11;
UPDATE customer SET customer_status = 1 WHERE customer_status = 0;
SELECT * FROM customer WHERE customer_name LIKE '%Ngh%';
SELECT * FROM service;
SELECT * FROM service LEFT JOIN rent_type ON rent_type.rent_type_id = service.rent_type_id LEFT JOIN service_type ON service_type.service_type_id = service.service_type_id;
SELECT * FROM rent_type;
SELECT * FROM service_type;
INSERT INTO service (service_name,service_area,service_cost,service_max_people,rent_type_id,service_type_id,standard_room,description_other_convenience,pool_area,number_of_floors) VALUES ("Villa",24000,200000,2,1,2,"normal","có hồ bơi",400,2);
SELECT * FROM service LEFT JOIN rent_type ON rent_type.rent_type_id = service.rent_type_id LEFT JOIN service_type ON service_type.service_type_id = service.service_type_id WHERE service_id=4;
UPDATE service SET service_name = "A",service_area = 122,service_cost = 10.2,service_max_people = 2,rent_type_id=2,service_type_id=1,standard_room="vip",description_other_convenience="free ăn sáng",pool_area=20.3,number_of_floors=2 WHERE service_id = 6;
UPDATE service SET service_status = 0 WHERE service_id = 1;
SELECT * FROM employee JOIN `position` ON `position`.position_id = employee.position_id JOIN education_degree ON education_degree.education_degree_id = employee.education_degree_id JOIN division ON division.division_id = employee.division_id JOIN `user` ON `user`.username = employee.username WHERE employee_status = 1;
SELECT * FROM `position`;
SELECT * FROM education_degree;
SELECT * FROM division;
INSERT INTO employee (employee_name,employee_birthday,employee_id_card,employee_salary,employee_phone,employee_email,employee_address,position_id,education_degree_id,division_id,username) VALUES ("A","2000-12-12","123123123",200,"090123123","abc@gmail.com","123ABC",1,1,1,"annguyen");